# For actual deployment
# Requires valid domain name for certbot

version: '3.9'

services:
  nginx-proxy-dep-test:
    container_name: nginx-proxy-dep-test
    image: "nginx:stable"
    depends_on:
      - "earthquake-hub-backend-dep-test"
      - "earthquake-hub-frontend-dep-test"
    networks:
      app-network:
        ipv4_address: 172.21.0.10
    ports:  # expose nginx ports to host
      - "80:80"
      - "443:443"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    volumes:
      - ./https_data/nginx.d:/etc/nginx/conf.d:ro              # Mount read-only access to nginx conf file.
                                                               # NOTE: Edit nginx.conf in this dir to reflect correct domain name of your server
      - ./https_data/certbot/www:/var/www/certbot:ro           # Certbot will write a token in this dir, served by nginx on well-known/acme-challenge/:80 route
      - ./https_data/certbot/conf:/etc/nginx/ssl:ro            # Certbot will write the certs into this (/etc/nginx/ssl), used by nginx as ssl_certificate and ssl_certificate_key under the directory /etc/nginx/ssl/live/<domain-name>/<fullchain-or-privkey>.pem;

  certbot:
    image: certbot/certbot
    volumes:
      - ./https_data/certbot/conf:/etc/letsencrypt:rw          # Run the following command to renew the certificates:
      - ./https_data/certbot/www:/var/www/certbot:rw           #   docker compose run --rm certbot renew

  ehub-frontend:
    container_name: ehub-frontend
    environment: # load env vars from docker compose --env-file
      REACT_APP_PUBLIC_VAPID_KEY: ${REACT_APP_PUBLIC_VAPID_KEY}
      REACT_APP_BACKEND: ${REACT_APP_BACKEND}
      REACT_APP_FDSNWS: ${REACT_APP_FDSNWS}
      REACT_APP_RS_FDSNWS: ${REACT_APP_RS_FDSNWS}
      REACT_APP_RINGSERVER_WS: ${REACT_APP_RINGSERVER_WS}
    image: "ghcr.io/upri-earthquake/earthquake-hub-frontend:latest"
    depends_on:
      - "earthquake-hub-backend-dep-test"
    expose:
      - "3000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.21.0.2

  ehub-backend:
    container_name: ehub-backend
    environment:
      MONGO_CONNX_TYPE: ${MONGO_CONNX_TYPE}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_NAME: ${MONGO_NAME}

      # webpush notifications VAPID keys
      PUBLIC_VAPID_KEY: ${PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${PRIVATE_VAPID_KEY}
      WEB_PUSH_CONTACT: ${WEB_PUSH_CONTACT}

      # Granular reverse-geolocation
      GEOSERVE_HOST: ${GEOSERVE_HOST}
      GEOSERVE_PORT: ${GEOSERVE_PORT}

      # production host domain (and for deployment testing)
      CLIENT_PROD_HOST: ${CLIENT_PROD_HOST}
      BACKEND_PROD_HOST: ${BACKEND_PROD_HOST}
      BACKEND_PROD_PORT: ${BACKEND_PROD_PORT}

      #ringserver host
      RINGSERVER_HOST: ${RINGSERVER_HOST}
      RINGSERVER_PORT: ${RINGSERVER_PORT}

      # jsonwebtoken keys
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
    depends_on:
      - "mongodb"
    image: "ghcr.io/upri-earthquake/earthquake-hub-backend:latest"
    expose:
      - "5000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.21.0.3

  ringserver:
    container_name: ringserver
    image: "ghcr.io/upri-earthquake/receiver-ringserver:latest"
    expose:
      - "16000"
      - "18000"
    networks:
      app-network:
        ipv4_address: 172.21.0.6
    ports:
      - "16000:16000" # make host's 16000 connect to RS's 16000
    volumes:
      - type: bind
        source: ./ringserver-configs
        target: /app/host-configs
    user: root
    entrypoint: /app/host-configs/entrypoint.sh

  mongodb:
    container_name: mongodb-dep-test
    image: "mongo:5.0"
    volumes:
      - type: volume
        source: earthquake-hub-mongodb-data
        target: /data/db
    expose:
      - "27017"
    networks:
      app-network:
        ipv4_address: 172.21.0.4

# TODO: Add admin-frontend
# TODO: Add admin-backend

# Geoserve is used to convert (long, lat) to city-names.
# The images are available as bare-metal builds in the server

  geoserve-db:
    build:
      context: ../hazdev-geoserve-ws
      dockerfile: Dockerfile-db
    image: "usgs/hazdev-geoserve-db:latest"
    environment:
      - DATALOAD_DIR=${DATALOAD_DIR}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_LOAD_TYPE=${DB_LOAD_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_ADMIN_DSN=${DB_ADMIN_DSN}
      - PGDATA=${PGDATA}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      # volume to store downloaded data files
      - ../hazdev-geoserve-ws/data/dataload:/tmp/dataload
      # volume to store database data files
      - ../hazdev-geoserve-ws/data/pgdata:/var/lib/postgresqsl/data/pgdata
    networks:
      app-network:
        ipv4_address: 172.21.0.6

  geoserve-ws:
    build:
      context: ../hazdev-geoserve-ws
      dockerfile: Dockerfile-ws
    image: "usgs/hazdev-geoserve-ws:latest"
    environment:
      - DB_DSN=${DB_DSN}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      # volumes for local dev
      - ../hazdev-geoserve-ws/src/htdocs:/var/www/apps/hazdev-geoserve-ws/htdocs
      - ../hazdev-geoserve-ws/src/lib:/var/www/apps/hazdev-geoserve-ws/lib
    expose:
      - "80"
    networks:
      app-network:
        ipv4_address: 172.21.0.7

volumes:
  earthquake-hub-mongodb-data:
    external: true # same volume used by other containers
    name: earthquake-hub-mongodb-data

networks:
  app-network:
    name: earthquake-hub-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16


