#!/usr/bin/env bash
set -Eeuo pipefail

umask 022

OUTPUT_DIR="${ADMIN_ACCESS_CONFIG_DIR:-./runtime/admin-access.d}"
OUTPUT_FILE="$OUTPUT_DIR/allow.conf"
RELOAD=false
DISABLE=false
CIDRS=()

usage() {
  cat >&2 <<'USAGE'
Usage:
  ./scripts/configure-admin-access.sh <CIDR> [<CIDR> ...] [--reload]
  ./scripts/configure-admin-access.sh --disable [--reload]

Examples:
  ./scripts/configure-admin-access.sh 10.20.12.0/22
  ./scripts/configure-admin-access.sh 203.0.113.44/32 --reload

The script canonicalizes each CIDR and writes only nginx `allow` directives.
With no generated allow directives, the tracked nginx configuration denies all
requests to /admin/ and /api/admin/.
USAGE
}

for argument in "$@"; do
  case "$argument" in
    --reload) RELOAD=true ;;
    --disable) DISABLE=true ;;
    --help|-h) usage; exit 0 ;;
    --*) printf 'Unknown option: %s\n' "$argument" >&2; usage; exit 64 ;;
    *) CIDRS+=("$argument") ;;
  esac
done

if [[ "$DISABLE" == true && ${#CIDRS[@]} -gt 0 ]]; then
  printf '%s\n' '--disable cannot be combined with CIDRs.' >&2
  exit 64
fi
if [[ "$DISABLE" == false && ${#CIDRS[@]} -eq 0 ]]; then
  usage
  exit 64
fi
if ! command -v python3 >/dev/null 2>&1; then
  printf '%s\n' 'python3 is required for strict CIDR validation.' >&2
  exit 69
fi

mkdir -p -- "$OUTPUT_DIR"
temporary="$(mktemp "$OUTPUT_DIR/.allow.conf.XXXXXX")"
backup=""
trap 'rm -f -- "${temporary:-}" "${backup:-}"' EXIT

if [[ "$DISABLE" == true ]]; then
  printf '# Generated by configure-admin-access.sh: no networks allowed.\n' > "$temporary"
else
  canonical="$({ printf '%s\n' "${CIDRS[@]}"; } | python3 -c '
import ipaddress
import sys

seen = set()
for raw in sys.stdin:
    value = raw.strip()
    if not value:
        continue
    if "/" not in value:
        raise SystemExit(f"CIDR prefix is required (use /32 for one IPv4 address): {value}")
    try:
        network = ipaddress.ip_network(value, strict=False)
    except ValueError as error:
        raise SystemExit(f"Invalid CIDR {value}: {error}")
    canonical = str(network)
    if canonical not in seen:
        print(canonical)
        seen.add(canonical)
')"
  {
    printf '# Generated by configure-admin-access.sh; do not edit manually.\n'
    while IFS= read -r network; do
      [[ -n "$network" ]] && printf 'allow %s;\n' "$network"
    done <<< "$canonical"
  } > "$temporary"
fi

chmod 0644 -- "$temporary"
if [[ -f "$OUTPUT_FILE" ]]; then
  backup="$(mktemp "$OUTPUT_DIR/.allow.conf.backup.XXXXXX")"
  cp -- "$OUTPUT_FILE" "$backup"
fi
mv -- "$temporary" "$OUTPUT_FILE"
temporary=""

if [[ "$RELOAD" == true ]]; then
  if ! docker inspect --format '{{.State.Running}}' nginx-proxy 2>/dev/null | grep -qx true; then
    printf '%s\n' 'nginx-proxy is not running; configuration was generated but not reloaded.' >&2
    exit 69
  fi
  if ! docker exec nginx-proxy nginx -t; then
    if [[ -n "$backup" ]]; then mv -- "$backup" "$OUTPUT_FILE"; else rm -f -- "$OUTPUT_FILE"; fi
    printf '%s\n' 'nginx validation failed; the previous generated allowlist was restored.' >&2
    exit 65
  fi
  docker exec nginx-proxy nginx -s reload
fi

if [[ "$DISABLE" == true ]]; then
  printf 'Admin access is fail-closed: no networks are allowed.\n'
else
  printf 'Generated %s with validated admin allow directives.\n' "$OUTPUT_FILE"
fi
